name: test
on: 
  push:
   branches:
     - main

jobs:
    defaults:
      run:
       shell: bash
       working-directory: /home/jkibari3/test


    test_runner:
        runs-on: [self-hosted]
        steps:
        - uses: actions/checkout@v2
        - name: get-env
          run: env
