name: test
on:
    push:
        branches:
            - master

jobs:
    test_runner:
        runs-on: [self-hosted]
        steps:
            - name: get-env
              run: env
              working-directory: /home/jkibari3/test 
	
