name: test
on: 
  push:
   branches:
     - master

jobs:
    test_runner:
        runs-on: [self-hosted,deb-git]
        steps:
        - name: get-env
          run: env

defaults:
  run:
    shell: bash
    working-directory: test
