name: test
on: 
  push:
   branches:
     - main

jobs:
    test_runner:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2
        - name: get-env
          run: env
          working-directory: ./jkibari2/test
